
const LILYPOND_VERSION = "2.20.0";


const CM_TO_PX = 37.794;

const LILY_TOP_MARGIN_DEFAULT = 0.5;
const LILY_BOTTOM_MARGIN_DEFAULT = 0.6;
const LILY_HORIZONTAL_MARGIN_DEFAULT = 1;
const LILY_STAFF_SIZE_DEFAULT = 20;

//const SYSTEM_SYSTEM_SPACING = 0.08;

const STAFF_HEAD_DEDUCTION = 0.06;	// extra width augment when system wrap added, cm per staff size



export {
	LILYPOND_VERSION,

	CM_TO_PX,

	LILY_TOP_MARGIN_DEFAULT,
	LILY_BOTTOM_MARGIN_DEFAULT,
	LILY_HORIZONTAL_MARGIN_DEFAULT,
	LILY_STAFF_SIZE_DEFAULT,
	//SYSTEM_SYSTEM_SPACING,

	STAFF_HEAD_DEDUCTION,
};
